### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by RonjaAnn** [KonstiDE/Bestagon#1]
Hallo Konsti,
hab einen Error wenn ich das Plug-In ausführen möchte:

An error has occurred while executing Python code: 

ValueError: could not convert string to float: '' 
Traceback (most recent call last):
  File "C:\Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Bestagon-master\bestagon.py", line 286, in run
    width = float(edit_width.text())
ValueError: could not convert string to float: ''

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f3 

Python Path:
C:\Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\road_slope_calculator
C:/OSGeo4W/apps/qgis/./python
C:/Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\ron\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/ron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\ron\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\ron\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
E:/Uni/DigitalImageAnalysis/BikePaths

<img width="298" alt="Screenshot 2023-03-31 221257" src="https://user-images.githubusercontent.com/116875684/229220769-f8873845-58c8-4e15-9e2c-f770fe41b91f.png">

Hoffe du kannst damit was anfangen

**Comment by KonstiDE** [comment]
No values were provided for with and height, thus, python tries to cast a float out of an empty string, that does not work.
Moreover, PyQgis does not trigger pythons standard library of errors (e.g. TypeError, ValueError, ...), however, Exceptions.

Fixed now.

**Comment by KonstiDE** [comment]
Projection is not being looked at, will be fixed in the next update

**Comment by KonstiDE** [comment]
The width and height scale now binds to the CRS of the layers. However, this also means, that the width and height have to be inserted in degrees, which is less comfortable than meters...
